FROM node:20-alpine
WORKDIR /app

# Debug-Informationen anzeigen
RUN node -v && npm -v && npm list -g

# Installiere notwendige globale Pakete
RUN npm install -g node-gyp

# Kopiere package.json und package-lock.json
COPY package*.json ./
RUN npm install

# Kopiere den Rest des Projekts
COPY . .

# Zeige den Inhalt des Verzeichnisses an
RUN ls -la && echo "Node.js version:" && node -v

EXPOSE 8080

# Starte den Vite-Entwicklungsserver
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 
